-- =============================================================================
-- THAIGER SUPPLEMENTS — Esquema completo de Supabase
--
-- Ejecuta este archivo en el SQL Editor de tu proyecto de Supabase.
-- Crea: users, products, orders, order_items, settings, las políticas RLS,
-- la función de descuento de inventario y los buckets de imágenes.
--
-- Es idempotente: se puede volver a ejecutar sobre un proyecto ya montado.
-- =============================================================================

-- ----------------------------------------------------------------- PERFILES
create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    name text,
    role text not null default 'user',
    avatar_url text,
    created_at timestamptz not null default now()
);

alter table public.users enable row level security;

drop policy if exists "Cada quien ve su perfil" on public.users;
create policy "Cada quien ve su perfil" on public.users
    for select using (auth.uid() = id);

drop policy if exists "Cada quien crea su perfil" on public.users;
create policy "Cada quien crea su perfil" on public.users
    for insert with check (auth.uid() = id);

drop policy if exists "Cada quien edita su perfil" on public.users;
create policy "Cada quien edita su perfil" on public.users
    for update using (auth.uid() = id);

-- Evita recursión infinita en las políticas que consultan el rol.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (select 1 from public.users where id = auth.uid() and role = 'admin');
$$;

drop policy if exists "Admins ven todos los perfiles" on public.users;
create policy "Admins ven todos los perfiles" on public.users
    for select using (public.is_admin());

-- El panel de administración cambia roles y da de baja cuentas.
drop policy if exists "Admins editan perfiles" on public.users;
create policy "Admins editan perfiles" on public.users
    for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins eliminan perfiles" on public.users;
create policy "Admins eliminan perfiles" on public.users
    for delete using (public.is_admin());

-- Un usuario no debe poder ascenderse a administrador editando su propio
-- perfil: este disparador conserva el rol salvo que quien edita ya sea admin.
create or replace function public.proteger_rol()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.role is distinct from old.role and not public.is_admin() then
        new.role := old.role;
    end if;
    return new;
end;
$$;

drop trigger if exists proteger_rol on public.users;
create trigger proteger_rol
    before update on public.users
    for each row execute function public.proteger_rol();

-- ---------------------------------------------------------------- PRODUCTOS
create table if not exists public.products (
    id bigint primary key generated by default as identity,
    name text not null,
    brand text not null,
    category text not null,
    description text default '',
    price1 numeric not null default 0,
    price2 numeric not null default 0,
    price3 numeric not null default 0,
    image_url text,
    stock integer not null default 0,
    is_on_sale boolean not null default false,
    discount_percent integer not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists products_brand_idx on public.products (brand);
create index if not exists products_category_idx on public.products (category);

alter table public.products enable row level security;

-- El catálogo es público; sólo el administrador escribe.
drop policy if exists "Catálogo público" on public.products;
create policy "Catálogo público" on public.products for select using (true);

drop policy if exists "Admins administran productos" on public.products;
create policy "Admins administran productos" on public.products
    for all using (public.is_admin()) with check (public.is_admin());

-- ------------------------------------------------------------------ PEDIDOS
create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    status text not null default 'Pago Pendiente',
    subtotal numeric not null default 0,
    shipping_cost numeric not null default 0,
    total numeric not null,
    tier smallint not null default 1,
    shipping_info jsonb,
    payment_info jsonb,
    created_at timestamptz not null default now()
);

-- Columnas añadidas después de la primera versión del esquema.
alter table public.orders add column if not exists subtotal numeric not null default 0;
alter table public.orders add column if not exists shipping_cost numeric not null default 0;
alter table public.orders add column if not exists tier smallint not null default 1;

create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists orders_created_idx on public.orders (created_at desc);

create table if not exists public.order_items (
    id uuid primary key default gen_random_uuid(),
    order_id uuid not null references public.orders(id) on delete cascade,
    product_id bigint references public.products(id) on delete set null,
    product_name text not null,
    quantity integer not null,
    price_at_purchase numeric not null
);

create index if not exists order_items_order_idx on public.order_items (order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Usuarios ven sus pedidos" on public.orders;
create policy "Usuarios ven sus pedidos" on public.orders
    for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Usuarios crean sus pedidos" on public.orders;
create policy "Usuarios crean sus pedidos" on public.orders
    for insert with check (auth.uid() = user_id);

drop policy if exists "Admins actualizan pedidos" on public.orders;
create policy "Admins actualizan pedidos" on public.orders
    for update using (public.is_admin());

drop policy if exists "Admins eliminan pedidos" on public.orders;
create policy "Admins eliminan pedidos" on public.orders
    for delete using (public.is_admin());

drop policy if exists "Usuarios ven sus artículos" on public.order_items;
create policy "Usuarios ven sus artículos" on public.order_items
    for select using (
        public.is_admin()
        or exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    );

drop policy if exists "Usuarios crean sus artículos" on public.order_items;
create policy "Usuarios crean sus artículos" on public.order_items
    for insert with check (
        exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    );

drop policy if exists "Admins eliminan artículos" on public.order_items;
create policy "Admins eliminan artículos" on public.order_items
    for delete using (public.is_admin());

-- ------------------------------------------------------------ CONFIGURACIÓN
-- Un único registro con la configuración editable desde el panel: contacto,
-- cuenta SPEI, umbrales de envío y de nivel, slides del carrusel y textos.
create table if not exists public.settings (
    id text primary key,
    value jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.settings enable row level security;

-- La tienda necesita leerla sin sesión (pie de página, checkout, carrusel).
drop policy if exists "Configuración pública" on public.settings;
create policy "Configuración pública" on public.settings for select using (true);

drop policy if exists "Admins editan la configuración" on public.settings;
create policy "Admins editan la configuración" on public.settings
    for all using (public.is_admin()) with check (public.is_admin());

insert into public.settings (id, value)
values ('site', '{}'::jsonb)
on conflict (id) do nothing;

-- ------------------------------------------------------- INVENTARIO (RPC)
create or replace function public.decrement_stock(product_id bigint, qty integer)
returns void
language sql
security definer
set search_path = public
as $$
    update public.products
       set stock = greatest(0, stock - qty)
     where id = product_id;
$$;

-- ------------------------------------------------------------- ALMACENAMIENTO
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "Imágenes públicas" on storage.objects;
create policy "Imágenes públicas" on storage.objects
    for select using (bucket_id in ('product-images', 'avatars'));

drop policy if exists "Usuarios autenticados suben imágenes" on storage.objects;
create policy "Usuarios autenticados suben imágenes" on storage.objects
    for insert to authenticated
    with check (bucket_id in ('product-images', 'avatars'));

-- =============================================================================
-- Después de ejecutar esto:
--   1. Crea tu cuenta desde /register en la app.
--   2. Conviértela en administradora:
--        update public.users set role = 'admin' where email = 'tu@correo.com';
--      (o bien: SUPABASE_URL=... SUPABASE_SERVICE_KEY=... node scripts/create-admin.js correo password)
--   3. Carga el catálogo de ejemplo:  node scripts/upload-supabase.js
--
-- Recuerda: el catálogo que se sube es de DEMOSTRACIÓN. Sustitúyelo por el
-- real y cambia la cuenta bancaria en el panel antes de vender.
-- =============================================================================
