-- =============================================================================
-- THAIGER SUPPLEMENTS — Esquema completo de Supabase
--
-- Ejecuta este archivo en el SQL Editor de tu proyecto de Supabase.
-- Crea: users, products, orders, order_items, políticas RLS, la función de
-- descuento de inventario y los buckets de imágenes.
-- =============================================================================

-- ----------------------------------------------------------------- PERFILES
create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    name text,
    role text not null default 'user',
    avatar_url text,
    created_at timestamptz not null default now()
);

alter table public.users enable row level security;

drop policy if exists "Cada quien ve su perfil" on public.users;
create policy "Cada quien ve su perfil" on public.users
    for select using (auth.uid() = id);

drop policy if exists "Cada quien crea su perfil" on public.users;
create policy "Cada quien crea su perfil" on public.users
    for insert with check (auth.uid() = id);

drop policy if exists "Cada quien edita su perfil" on public.users;
create policy "Cada quien edita su perfil" on public.users
    for update using (auth.uid() = id);

-- Evita recursión infinita en las políticas que consultan el rol.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (select 1 from public.users where id = auth.uid() and role = 'admin');
$$;

drop policy if exists "Admins ven todos los perfiles" on public.users;
create policy "Admins ven todos los perfiles" on public.users
    for select using (public.is_admin());

-- ---------------------------------------------------------------- PRODUCTOS
create table if not exists public.products (
    id bigint primary key generated by default as identity,
    name text not null,
    brand text not null,
    category text not null,
    description text default '',
    price1 numeric not null default 0,
    price2 numeric not null default 0,
    price3 numeric not null default 0,
    image_url text,
    stock integer not null default 0,
    is_on_sale boolean not null default false,
    discount_percent integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- El catálogo es público; sólo el administrador escribe.
drop policy if exists "Catálogo público" on public.products;
create policy "Catálogo público" on public.products for select using (true);

drop policy if exists "Admins administran productos" on public.products;
create policy "Admins administran productos" on public.products
    for all using (public.is_admin()) with check (public.is_admin());

-- ------------------------------------------------------------------ PEDIDOS
create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    status text not null default 'Pago Pendiente',
    total numeric not null,
    shipping_info jsonb,
    payment_info jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.order_items (
    id uuid primary key default gen_random_uuid(),
    order_id uuid not null references public.orders(id) on delete cascade,
    product_id bigint references public.products(id) on delete set null,
    product_name text not null,
    quantity integer not null,
    price_at_purchase numeric not null
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Usuarios ven sus pedidos" on public.orders;
create policy "Usuarios ven sus pedidos" on public.orders
    for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Usuarios crean sus pedidos" on public.orders;
create policy "Usuarios crean sus pedidos" on public.orders
    for insert with check (auth.uid() = user_id);

drop policy if exists "Admins actualizan pedidos" on public.orders;
create policy "Admins actualizan pedidos" on public.orders
    for update using (public.is_admin());

drop policy if exists "Usuarios ven sus artículos" on public.order_items;
create policy "Usuarios ven sus artículos" on public.order_items
    for select using (
        public.is_admin()
        or exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    );

drop policy if exists "Usuarios crean sus artículos" on public.order_items;
create policy "Usuarios crean sus artículos" on public.order_items
    for insert with check (
        exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    );

-- ------------------------------------------------------- INVENTARIO (RPC)
create or replace function public.decrement_stock(product_id bigint, qty integer)
returns void
language sql
security definer
set search_path = public
as $$
    update public.products
       set stock = greatest(0, stock - qty)
     where id = product_id;
$$;

-- ------------------------------------------------------------- ALMACENAMIENTO
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "Imágenes públicas" on storage.objects;
create policy "Imágenes públicas" on storage.objects
    for select using (bucket_id in ('product-images', 'avatars'));

drop policy if exists "Usuarios autenticados suben imágenes" on storage.objects;
create policy "Usuarios autenticados suben imágenes" on storage.objects
    for insert to authenticated
    with check (bucket_id in ('product-images', 'avatars'));

-- =============================================================================
-- Después de ejecutar esto:
--   1. Crea tu cuenta desde /register en la app.
--   2. Conviértela en administradora:
--        update public.users set role = 'admin' where email = 'tu@correo.com';
--   3. Carga el catálogo base:  node scripts/upload-supabase.js
-- =============================================================================
