-- =============================================================================
-- THAIGER SUPPLEMENTS — Esquema completo de Supabase
--
-- Ejecuta este archivo en el SQL Editor de tu proyecto de Supabase.
-- Crea: users, products, orders, order_items, settings, las políticas RLS,
-- la función de descuento de inventario y los buckets de imágenes.
--
-- Es idempotente: se puede volver a ejecutar sobre un proyecto ya montado.
-- =============================================================================

-- ----------------------------------------------------------------- PERFILES
create table if not exists public.users (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    name text,
    role text not null default 'user',
    avatar_url text,
    created_at timestamptz not null default now()
);

alter table public.users enable row level security;

drop policy if exists "Cada quien ve su perfil" on public.users;
create policy "Cada quien ve su perfil" on public.users
    for select using (auth.uid() = id);

drop policy if exists "Cada quien crea su perfil" on public.users;
create policy "Cada quien crea su perfil" on public.users
    for insert with check (auth.uid() = id);

drop policy if exists "Cada quien edita su perfil" on public.users;
create policy "Cada quien edita su perfil" on public.users
    for update using (auth.uid() = id);

-- Evita recursión infinita en las políticas que consultan el rol.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (select 1 from public.users where id = auth.uid() and role = 'admin');
$$;

drop policy if exists "Admins ven todos los perfiles" on public.users;
create policy "Admins ven todos los perfiles" on public.users
    for select using (public.is_admin());

-- El panel de administración cambia roles y da de baja cuentas.
drop policy if exists "Admins editan perfiles" on public.users;
create policy "Admins editan perfiles" on public.users
    for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins eliminan perfiles" on public.users;
create policy "Admins eliminan perfiles" on public.users
    for delete using (public.is_admin());

-- Un usuario no debe poder ascenderse a administrador editando su propio
-- perfil: este disparador conserva el rol salvo que quien edita ya sea admin.
create or replace function public.proteger_rol()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.role is distinct from old.role and not public.is_admin() then
        new.role := old.role;
    end if;
    return new;
end;
$$;

drop trigger if exists proteger_rol on public.users;
create trigger proteger_rol
    before update on public.users
    for each row execute function public.proteger_rol();

-- ---------------------------------------------------------------- PRODUCTOS
create table if not exists public.products (
    id bigint primary key generated by default as identity,
    name text not null,
    brand text not null,
    category text not null,
    description text default '',
    price1 numeric not null default 0,
    price2 numeric not null default 0,
    price3 numeric not null default 0,
    image_url text,
    stock integer not null default 0,
    is_on_sale boolean not null default false,
    discount_percent integer not null default 0,
    created_at timestamptz not null default now()
);

create index if not exists products_brand_idx on public.products (brand);
create index if not exists products_category_idx on public.products (category);

-- Peso y medidas del paquete, para cotizar el envío con la paquetería.
-- Valores por defecto razonables para un bote de suplemento: se afinan en el
-- formulario de cada producto.
alter table public.products add column if not exists weight_g integer not null default 500;
alter table public.products add column if not exists length_cm integer not null default 20;
alter table public.products add column if not exists width_cm integer not null default 15;
alter table public.products add column if not exists height_cm integer not null default 10;

alter table public.products enable row level security;

-- El catálogo es público; sólo el administrador escribe.
drop policy if exists "Catálogo público" on public.products;
create policy "Catálogo público" on public.products for select using (true);

drop policy if exists "Admins administran productos" on public.products;
create policy "Admins administran productos" on public.products
    for all using (public.is_admin()) with check (public.is_admin());

-- ------------------------------------------------------------------ PEDIDOS
create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    status text not null default 'Pago Pendiente',
    subtotal numeric not null default 0,
    shipping_cost numeric not null default 0,
    total numeric not null,
    tier smallint not null default 1,
    shipping_info jsonb,
    payment_info jsonb,
    created_at timestamptz not null default now()
);

-- Columnas añadidas después de la primera versión del esquema.
alter table public.orders add column if not exists subtotal numeric not null default 0;
alter table public.orders add column if not exists shipping_cost numeric not null default 0;
alter table public.orders add column if not exists tier smallint not null default 1;
-- Pasarela de pago y guía de envío (segunda versión del esquema).
alter table public.orders add column if not exists payment_provider text not null default 'spei';
alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists shipping_quote jsonb;
alter table public.orders add column if not exists shipment jsonb;

create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists orders_created_idx on public.orders (created_at desc);

create table if not exists public.order_items (
    id uuid primary key default gen_random_uuid(),
    order_id uuid not null references public.orders(id) on delete cascade,
    product_id bigint references public.products(id) on delete set null,
    product_name text not null,
    quantity integer not null,
    price_at_purchase numeric not null
);

create index if not exists order_items_order_idx on public.order_items (order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Usuarios ven sus pedidos" on public.orders;
create policy "Usuarios ven sus pedidos" on public.orders
    for select using (auth.uid() = user_id or public.is_admin());

-- OJO: no hay política de INSERT sobre orders, y es deliberado.
-- Un insert directo dejaría que el navegador eligiera subtotal, total, tier y
-- status (la RLS sólo sabe comprobar que el user_id sea el suyo). Los pedidos
-- se crean únicamente con public.create_order(), que recalcula todo contra el
-- catálogo. Si alguna vez vuelve a hacer falta, se crea aquí a conciencia.
drop policy if exists "Usuarios crean sus pedidos" on public.orders;

drop policy if exists "Admins actualizan pedidos" on public.orders;
create policy "Admins actualizan pedidos" on public.orders
    for update using (public.is_admin());

drop policy if exists "Admins eliminan pedidos" on public.orders;
create policy "Admins eliminan pedidos" on public.orders
    for delete using (public.is_admin());

drop policy if exists "Usuarios ven sus artículos" on public.order_items;
create policy "Usuarios ven sus artículos" on public.order_items
    for select using (
        public.is_admin()
        or exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid())
    );

-- Igual que arriba: las líneas del pedido las escribe create_order().
drop policy if exists "Usuarios crean sus artículos" on public.order_items;

drop policy if exists "Admins eliminan artículos" on public.order_items;
create policy "Admins eliminan artículos" on public.order_items
    for delete using (public.is_admin());

-- ------------------------------------------------------------ CONFIGURACIÓN
-- Un único registro con la configuración editable desde el panel: contacto,
-- cuenta SPEI, umbrales de envío y de nivel, slides del carrusel y textos.
create table if not exists public.settings (
    id text primary key,
    value jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.settings enable row level security;

-- La tienda necesita leerla sin sesión (pie de página, checkout, carrusel).
drop policy if exists "Configuración pública" on public.settings;
create policy "Configuración pública" on public.settings for select using (true);

drop policy if exists "Admins editan la configuración" on public.settings;
create policy "Admins editan la configuración" on public.settings
    for all using (public.is_admin()) with check (public.is_admin());

insert into public.settings (id, value)
values ('site', '{}'::jsonb)
on conflict (id) do nothing;

-- ------------------------------------------------------ COTIZACIONES DE ENVÍO
-- La Edge Function `cotizar-envio` pide tarifas a la paquetería y las guarda
-- aquí con caducidad. Al crear el pedido, el cliente sólo manda el id de la
-- cotización y el de la tarifa: el precio del envío se toma de esta tabla, no
-- del navegador. Sólo escribe aquí la service_role (no hay política de INSERT).
create table if not exists public.shipping_quotes (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    provider text not null,
    destination_zip text not null,
    package jsonb not null,
    rates jsonb not null,
    created_at timestamptz not null default now(),
    expires_at timestamptz not null
);

create index if not exists shipping_quotes_user_idx on public.shipping_quotes (user_id, created_at desc);

alter table public.shipping_quotes enable row level security;

drop policy if exists "Cada quien ve sus cotizaciones" on public.shipping_quotes;
create policy "Cada quien ve sus cotizaciones" on public.shipping_quotes
    for select using (auth.uid() = user_id or public.is_admin());

-- ------------------------------------------------------ CREACIÓN DEL PEDIDO
-- Ésta es la frontera de seguridad del cobro.
--
-- El navegador sólo manda QUÉ y CUÁNTO. Los precios, el nivel, el envío y el
-- total se recalculan aquí contra el catálogo, el stock se valida y se descuenta
-- en la MISMA transacción, y el estatus lo fija el servidor. Por eso `orders` y
-- `order_items` no tienen política de INSERT: si la tuvieran, cualquiera con la
-- anon key podría registrar un pedido de $1 marcado como pagado.
--
-- CUIDADO AL TOCAR PRECIOS: esta aritmética es el espejo de src/lib/pricing.js.
-- Si cambias una, cambia la otra o el cliente verá un total y se le cobrará otro.

/** Precio unitario según el nivel vigente, con la oferta ya aplicada. */
create or replace function public.precio_unitario(p public.products, p_tier smallint)
returns numeric
language sql
immutable
set search_path = public
as $$
    -- Igual que getTierBasePrice(): si el precio del nivel no es mayor a cero,
    -- se cae al precio público en lugar de regalar el producto.
    select case
               when p.is_on_sale
                    and p.discount_percent > 0
                    and p.discount_percent < 100
               then base * (1 - p.discount_percent::numeric / 100)
               else base
           end
      from (
          select case
                     when p_tier = 3 and p.price3 > 0 then p.price3
                     when p_tier = 2 and p.price2 > 0 then p.price2
                     else p.price1
                 end as base
      ) as nivel;
$$;

-- La firma cambió (cuarto parámetro): se retira la versión anterior para que
-- no queden dos sobrecargas y PostgREST no sepa a cuál llamar.
drop function if exists public.create_order(jsonb, jsonb, jsonb);

/**
 * Registra un pedido completo. Devuelve el pedido con sus líneas, en el mismo
 * formato que espera `supabaseBackend.orders.create`.
 *
 *   p_items:         [{"product_id": 1, "quantity": 2}, ...]
 *   p_shipping:      {"fullName","phone","address","city","zip","notes"}
 *   p_payment:       {"provider": "spei" | "mercadopago", "concepto", "banco"}
 *   p_shipping_rate: {"quote_id", "rate_id"} — tarifa cotizada, o null para la
 *                    regla fija de la tienda.
 */
create or replace function public.create_order(
    p_items jsonb,
    p_shipping jsonb,
    p_payment jsonb,
    p_shipping_rate jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user        uuid := auth.uid();
    v_cfg         jsonb;
    v_tier2       numeric;
    v_tier3       numeric;
    v_free_from   numeric;
    v_ship_cost   numeric;
    v_list_total  numeric := 0;
    v_subtotal    numeric := 0;
    v_shipping    numeric := 0;
    v_tier        smallint := 1;
    v_lineas      jsonb := '[]'::jsonb;
    v_envio       jsonb;
    v_concepto    text;
    v_provider    text;
    v_quote       public.shipping_quotes;
    v_rate        jsonb;
    v_ship_quote  jsonb := null;
    v_order       public.orders;
    v_items       jsonb;
    v_prod        public.products;
    r             record;
begin
    if v_user is null then
        raise exception 'Necesitas iniciar sesión para comprar.';
    end if;

    if p_items is null
       or jsonb_typeof(p_items) <> 'array'
       or jsonb_array_length(p_items) = 0 then
        raise exception 'El carrito está vacío.';
    end if;

    -- Dirección: los mismos campos obligatorios que pide el checkout.
    if coalesce(btrim(p_shipping->>'fullName'), '') = ''
       or coalesce(btrim(p_shipping->>'phone'), '') = ''
       or coalesce(btrim(p_shipping->>'address'), '') = ''
       or coalesce(btrim(p_shipping->>'city'), '') = ''
       or coalesce(btrim(p_shipping->>'zip'), '') = '' then
        raise exception 'Faltan datos de la dirección de envío.';
    end if;

    -- Umbrales configurados desde el panel (con los de fábrica como respaldo).
    select value into v_cfg from public.settings where id = 'site';
    v_tier2     := coalesce((v_cfg->'tiers'->>'tier2From')::numeric, 10000);
    v_tier3     := coalesce((v_cfg->'tiers'->>'tier3From')::numeric, 20000);
    v_free_from := coalesce((v_cfg->'shipping'->>'freeFrom')::numeric, 5000);
    v_ship_cost := coalesce((v_cfg->'shipping'->>'cost')::numeric, 250);
    if v_tier3 < v_tier2 then v_tier3 := v_tier2; end if;

    -- Se bloquean las filas del catálogo SIEMPRE en orden de id: si dos carritos
    -- comparten productos, uno espera al otro en vez de cruzarse (y dos compras
    -- de la última unidad no pasan las dos). El orden fijo evita el interbloqueo.
    perform 1
       from public.products
      where id in (
                select distinct (item->>'product_id')::bigint
                  from jsonb_array_elements(p_items) as item
            )
      order by id
        for update;

    -- Primera pasada: validar y sumar a precio de lista (el nivel se decide con
    -- precios de lista, para que el escalón no dependa del descuento).
    for r in
        select (item->>'product_id')::bigint                   as pid,
               floor(coalesce((item->>'quantity')::numeric, 0))::int as qty
          from jsonb_array_elements(p_items) as item
    loop
        select * into v_prod from public.products where id = r.pid;

        if not found then
            raise exception 'El producto "%" ya no está disponible.', r.pid;
        end if;
        if r.qty < 1 then
            raise exception 'Hay una cantidad inválida en el carrito.';
        end if;
        if r.qty > v_prod.stock then
            raise exception 'Sólo quedan % unidades de "%".', v_prod.stock, v_prod.name;
        end if;

        v_list_total := v_list_total + v_prod.price1 * r.qty;
        v_lineas := v_lineas || jsonb_build_object('pid', r.pid, 'qty', r.qty);
    end loop;

    if v_list_total >= v_tier3 then
        v_tier := 3;
    elsif v_list_total >= v_tier2 then
        v_tier := 2;
    else
        v_tier := 1;
    end if;

    -- Segunda pasada: ya con el nivel decidido, el precio que se cobra.
    for r in
        select (linea->>'pid')::bigint as pid,
               (linea->>'qty')::int    as qty
          from jsonb_array_elements(v_lineas) as linea
    loop
        select * into v_prod from public.products where id = r.pid;
        -- Redondeado ANTES de multiplicar, igual que computeCartTotals(): el
        -- subtotal tiene que ser la suma exacta de los price_at_purchase.
        v_subtotal := v_subtotal + round(public.precio_unitario(v_prod, v_tier), 2) * r.qty;
    end loop;

    v_subtotal := round(v_subtotal, 2);

    -- Envío: la regla fija de la tienda, o la tarifa que cotizó la paquetería.
    -- La tarifa se lee de shipping_quotes (la escribió la Edge Function), nunca
    -- del parámetro: el cliente sólo elige cuál, no cuánto.
    if p_shipping_rate is not null
       and jsonb_typeof(p_shipping_rate) = 'object'
       and coalesce(p_shipping_rate->>'quote_id', '') <> '' then

        select * into v_quote
          from public.shipping_quotes
         where id = (p_shipping_rate->>'quote_id')::uuid
           and user_id = v_user;

        if not found then
            raise exception 'La cotización de envío ya no es válida. Vuelve a cotizar.';
        end if;
        if v_quote.expires_at < now() then
            raise exception 'La cotización de envío caducó. Vuelve a cotizar.';
        end if;
        if v_quote.destination_zip <> left(btrim(p_shipping->>'zip'), 10) then
            raise exception 'La cotización de envío es para otro código postal. Vuelve a cotizar.';
        end if;

        select linea into v_rate
          from jsonb_array_elements(v_quote.rates) as linea
         where linea->>'id' = p_shipping_rate->>'rate_id';

        if v_rate is null then
            raise exception 'La tarifa de envío elegida ya no está disponible. Vuelve a cotizar.';
        end if;

        v_shipping := round((v_rate->>'amount')::numeric, 2);
        v_ship_quote := jsonb_build_object(
            'quote_id', v_quote.id,
            'provider', v_quote.provider,
            'rate',     v_rate,
            'package',  v_quote.package
        );
    else
        v_shipping := v_ship_cost;
    end if;

    -- El envío gratis es una promesa de la tienda y se cumple también con
    -- tarifa cotizada: la guía se sigue generando con la tarifa, pero la absorbe
    -- la tienda.
    if v_subtotal = 0 or v_subtotal >= v_free_from then
        v_shipping := 0;
    end if;

    -- El texto que escribió una persona se recorta aquí también: la RPC es
    -- pública para quien tenga sesión, así que no puede fiarse del front.
    v_envio := jsonb_build_object(
        'fullName', left(btrim(p_shipping->>'fullName'), 90),
        'phone',    left(btrim(p_shipping->>'phone'), 25),
        'address',  left(btrim(p_shipping->>'address'), 160),
        'city',     left(btrim(p_shipping->>'city'), 60),
        'zip',      left(btrim(p_shipping->>'zip'), 10),
        'notes',    left(btrim(coalesce(p_shipping->>'notes', '')), 300)
    );

    v_concepto := left(btrim(coalesce(p_payment->>'concepto', '')), 24);
    if v_concepto = '' then
        v_concepto := 'TH-' || upper(substr(md5(random()::text), 1, 4));
    end if;

    -- Sólo las pasarelas que la tienda conoce; cualquier otra cosa es SPEI.
    v_provider := case when p_payment->>'provider' = 'mercadopago' then 'mercadopago' else 'spei' end;

    insert into public.orders (user_id, status, subtotal, shipping_cost, total, tier,
                               shipping_info, payment_info, payment_provider, shipping_quote)
    values (
        v_user,
        'Pago Pendiente',                      -- el estatus nunca lo elige el cliente
        v_subtotal,
        v_shipping,
        v_subtotal + v_shipping,
        v_tier,
        v_envio,
        jsonb_build_object(
            'method',   case when v_provider = 'mercadopago' then 'Mercado Pago' else 'SPEI' end,
            'concepto', v_concepto,
            'banco',    left(btrim(coalesce(p_payment->>'banco', '')), 60)
        ),
        v_provider,
        v_ship_quote
    )
    returning * into v_order;

    -- Las líneas, con el precio ya resuelto, y el descuento de inventario en la
    -- misma transacción: si algo falla aquí, el pedido entero se deshace.
    with nuevas as (
        insert into public.order_items (order_id, product_id, product_name, quantity, price_at_purchase)
        select v_order.id,
               p.id,
               p.name,
               (linea->>'qty')::int,
               round(public.precio_unitario(p, v_tier), 2)
          from jsonb_array_elements(v_lineas) as linea
          join public.products p on p.id = (linea->>'pid')::bigint
        returning product_id, product_name, quantity, price_at_purchase
    )
    select coalesce(jsonb_agg(to_jsonb(nuevas)), '[]'::jsonb) into v_items from nuevas;

    update public.products p
       set stock = greatest(0, p.stock - (linea->>'qty')::int)
      from jsonb_array_elements(v_lineas) as linea
     where p.id = (linea->>'pid')::bigint;

    return to_jsonb(v_order) || jsonb_build_object('order_items', v_items);
end;
$$;

-- Sólo quien tiene sesión puede comprar. `public` incluye a `anon`.
revoke execute on function public.create_order(jsonb, jsonb, jsonb, jsonb) from public;
grant  execute on function public.create_order(jsonb, jsonb, jsonb, jsonb) to authenticated;

-- La RPC `decrement_stock` de la primera versión era `security definer` y
-- quedaba abierta a cualquiera con la anon key: se podía agotar un producto
-- ajeno (o inflarlo mandando una cantidad negativa). Ya no hace falta, porque
-- create_order() descuenta el inventario. Se elimina si quedó de antes.
drop function if exists public.decrement_stock(bigint, integer);

-- ------------------------------------------------------- CONFIRMACIÓN DEL PAGO
-- La llama la Edge Function `mp-webhook` con la service_role, después de
-- verificar la firma de Mercado Pago y de consultar el pago en su API. Es la
-- ÚNICA forma de que un pedido pase a «Pagado»: ni el cliente ni el panel
-- pueden hacerlo (el panel puede moverlo a los estatus de operación, pero
-- `paid_at` sólo lo pone esta función).
create or replace function public.marcar_pedido_pagado(
    p_order_id  uuid,
    p_provider  text,
    p_reference text,
    p_amount    numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_order public.orders;
begin
    select * into v_order from public.orders where id = p_order_id for update;

    if not found then
        raise exception 'El pedido % no existe.', p_order_id;
    end if;

    -- Mercado Pago reintenta las notificaciones: la segunda vez no pasa nada.
    if v_order.paid_at is not null then
        return to_jsonb(v_order) || '{"ya_estaba_pagado": true}'::jsonb;
    end if;

    if abs(v_order.total - p_amount) > 0.01 then
        raise exception 'El monto pagado (%) no coincide con el total del pedido (%).', p_amount, v_order.total;
    end if;

    if v_order.status <> 'Pago Pendiente' then
        raise exception 'El pedido está en estatus "%": no se puede marcar como pagado.', v_order.status;
    end if;

    update public.orders
       set status            = 'Pagado',
           paid_at           = now(),
           payment_provider  = p_provider,
           payment_reference = p_reference
     where id = p_order_id
    returning * into v_order;

    return to_jsonb(v_order);
end;
$$;

revoke execute on function public.marcar_pedido_pagado(uuid, text, text, numeric) from public, anon, authenticated;
grant  execute on function public.marcar_pedido_pagado(uuid, text, text, numeric) to service_role;

-- ------------------------------------------------------------ NOTIFICACIONES
-- Cada pedido nuevo y cada cambio de estatus avisa a la Edge Function
-- `notificar-pedido`, que manda los correos. Se configura una vez, con la URL
-- del proyecto y un secreto compartido que la función comprueba:
--
--   select public.configurar_notificaciones(
--       'https://<ref>.supabase.co/functions/v1/notificar-pedido',
--       '<el mismo valor que NOTIFY_SECRET en los secretos de la función>'
--   );
--
-- Requiere tener activados los Database Webhooks del proyecto
-- (Dashboard → Database → Webhooks → Enable), que es lo que instala
-- `supabase_functions.http_request`.
create or replace function public.configurar_notificaciones(p_url text, p_secret text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_headers text := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-thaiger-secret', p_secret
    )::text;
begin
    execute 'drop trigger if exists notificar_pedido_nuevo on public.orders';
    execute 'drop trigger if exists notificar_pedido_estatus on public.orders';

    execute format(
        'create trigger notificar_pedido_nuevo after insert on public.orders
            for each row execute function supabase_functions.http_request(%L, %L, %L, %L, %L)',
        p_url, 'POST', v_headers, '{}', '5000'
    );

    -- Sólo cuando cambia el estatus: editar la dirección no manda correo.
    execute format(
        'create trigger notificar_pedido_estatus after update on public.orders
            for each row when (old.status is distinct from new.status)
            execute function supabase_functions.http_request(%L, %L, %L, %L, %L)',
        p_url, 'POST', v_headers, '{}', '5000'
    );
end;
$$;

revoke execute on function public.configurar_notificaciones(text, text) from public, anon, authenticated;

-- ------------------------------------------------------------- ALMACENAMIENTO
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do nothing;

drop policy if exists "Imágenes públicas" on storage.objects;
create policy "Imágenes públicas" on storage.objects
    for select using (bucket_id in ('product-images', 'avatars'));

-- Las fotos del catálogo son del catálogo: sólo el administrador las toca.
-- (Antes bastaba con tener cuenta, así que cualquier cliente registrado podía
-- escribir en el bucket público de la tienda.)
drop policy if exists "Usuarios autenticados suben imágenes" on storage.objects;

drop policy if exists "Admins gestionan fotos de producto" on storage.objects;
create policy "Admins gestionan fotos de producto" on storage.objects
    for all to authenticated
    using (bucket_id = 'product-images' and public.is_admin())
    with check (bucket_id = 'product-images' and public.is_admin());

-- Cada quien escribe su avatar, y sólo dentro de su propia carpeta:
-- avatars/<auth.uid()>/<archivo>. Así nadie pisa la foto de otra persona.
drop policy if exists "Cada quien gestiona su avatar" on storage.objects;
create policy "Cada quien gestiona su avatar" on storage.objects
    for all to authenticated
    using (
        bucket_id = 'avatars'
        and (storage.foldername(name))[1] = auth.uid()::text
    )
    with check (
        bucket_id = 'avatars'
        and (storage.foldername(name))[1] = auth.uid()::text
    );

-- =============================================================================
-- Después de ejecutar esto:
--   1. Crea tu cuenta desde /register en la app.
--   2. Conviértela en administradora:
--        update public.users set role = 'admin' where email = 'tu@correo.com';
--      (o bien: SUPABASE_URL=... SUPABASE_SERVICE_KEY=... node scripts/create-admin.js correo password)
--   3. Carga el catálogo de ejemplo:  node scripts/upload-supabase.js
--
-- Recuerda: el catálogo que se sube es de DEMOSTRACIÓN. Sustitúyelo por el
-- real y cambia la cuenta bancaria en el panel antes de vender.
-- =============================================================================
